// Code generated by sqlc. DO NOT EDIT.
// Source: internal/store/sql/community_info.sql
package queries

import (
	"context"
)

const upsertCommunityInfo = `
INSERT INTO community_info (slug, title, body)
VALUES ($1, $2, $3)
ON CONFLICT (slug) DO UPDATE
  SET title = EXCLUDED.title, body = EXCLUDED.body, updated_at = now()
RETURNING id, slug, title, body, created_at, updated_at
`

type UpsertCommunityInfoParams struct {
	Slug  string
	Title string
	Body  string
}

func (q *Queries) UpsertCommunityInfo(ctx context.Context, p UpsertCommunityInfoParams) (CommunityInfo, error) {
	var c CommunityInfo
	err := q.db.QueryRow(ctx, upsertCommunityInfo,
		p.Slug, p.Title, p.Body,
	).Scan(&c.ID, &c.Slug, &c.Title, &c.Body, &c.CreatedAt, &c.UpdatedAt)
	return c, err
}

const getCommunityInfoBySlug = `
SELECT id, slug, title, body, created_at, updated_at
FROM community_info
WHERE slug = $1
`

func (q *Queries) GetCommunityInfoBySlug(ctx context.Context, slug string) (CommunityInfo, error) {
	var c CommunityInfo
	err := q.db.QueryRow(ctx, getCommunityInfoBySlug, slug).Scan(
		&c.ID, &c.Slug, &c.Title, &c.Body, &c.CreatedAt, &c.UpdatedAt,
	)
	return c, err
}

const searchCommunityInfo = `
SELECT
    id,
    slug,
    title,
    body,
    ts_rank(search_vector, plainto_tsquery('english', $1)) AS rank
FROM community_info
WHERE search_vector @@ plainto_tsquery('english', $1)
ORDER BY rank DESC
LIMIT $2
`

func (q *Queries) SearchCommunityInfo(ctx context.Context, query string, resultLimit int32) ([]SearchCommunityInfoRow, error) {
	rows, err := q.db.Query(ctx, searchCommunityInfo, query, resultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []SearchCommunityInfoRow
	for rows.Next() {
		var r SearchCommunityInfoRow
		if err := rows.Scan(&r.ID, &r.Slug, &r.Title, &r.Body, &r.Rank); err != nil {
			return nil, err
		}
		results = append(results, r)
	}
	return results, rows.Err()
}
