// Code generated by sqlc. DO NOT EDIT.
// Source: internal/store/sql/members.sql
package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgxpool"
)

type Queries struct {
	db *pgxpool.Pool
}

func New(db *pgxpool.Pool) *Queries {
	return &Queries{db: db}
}

const searchMembers = `
SELECT
    m.id,
    m.full_name,
    m.headline,
    m.bio,
    m.location,
    m.links,
    ts_rank(m.search_vector, plainto_tsquery('english', $1)) AS rank
FROM members m
WHERE m.is_public = TRUE
  AND m.search_vector @@ plainto_tsquery('english', $1)
ORDER BY rank DESC
LIMIT $2
`

func (q *Queries) SearchMembers(ctx context.Context, query string, resultLimit int32) ([]SearchMembersRow, error) {
	rows, err := q.db.Query(ctx, searchMembers, query, resultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []SearchMembersRow
	for rows.Next() {
		var r SearchMembersRow
		if err := rows.Scan(&r.ID, &r.FullName, &r.Headline, &r.Bio, &r.Location, &r.Links, &r.Rank); err != nil {
			return nil, err
		}
		results = append(results, r)
	}
	return results, rows.Err()
}

const getMemberByID = `
SELECT id, full_name, headline, bio, location, links, is_public, created_at, updated_at
FROM members
WHERE id = $1
`

func (q *Queries) GetMemberByID(ctx context.Context, id uuid.UUID) (Member, error) {
	var m Member
	err := q.db.QueryRow(ctx, getMemberByID, id).Scan(
		&m.ID, &m.FullName, &m.Headline, &m.Bio, &m.Location, &m.Links, &m.IsPublic, &m.CreatedAt, &m.UpdatedAt,
	)
	return m, err
}

const createMember = `
INSERT INTO members (full_name, headline, bio, location, email, links, is_public)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, full_name, headline, bio, location, links, is_public, created_at, updated_at
`

type CreateMemberParams struct {
	FullName string
	Headline *string
	Bio      *string
	Location *string
	Email    *string
	Links    []byte
	IsPublic bool
}

func (q *Queries) CreateMember(ctx context.Context, p CreateMemberParams) (Member, error) {
	var m Member
	err := q.db.QueryRow(ctx, createMember,
		p.FullName, p.Headline, p.Bio, p.Location, p.Email, p.Links, p.IsPublic,
	).Scan(&m.ID, &m.FullName, &m.Headline, &m.Bio, &m.Location, &m.Links, &m.IsPublic, &m.CreatedAt, &m.UpdatedAt)
	return m, err
}

const listMemberTags = `
SELECT t.name
FROM tags t
JOIN member_tags mt ON mt.tag_id = t.id
WHERE mt.member_id = $1
`

func (q *Queries) ListMemberTags(ctx context.Context, memberID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listMemberTags, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var names []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		names = append(names, name)
	}
	return names, rows.Err()
}
