// Code generated by sqlc. DO NOT EDIT.
// This file mirrors what `sqlc generate` produces from migrations/ + sql/.
// It's checked in so the project builds before you run sqlc yourself;
// regenerate it any time you change a .sql file (see scripts/gen.sh).
package queries

import (
	"time"

	"github.com/google/uuid"
)

type Member struct {
	ID        uuid.UUID `json:"id"`
	FullName  string    `json:"full_name"`
	Headline  *string   `json:"headline"`
	Bio       *string   `json:"bio"`
	Location  *string   `json:"location"`
	Email     *string   `json:"email,omitempty"`
	Links     []byte    `json:"links"` // raw JSONB
	IsPublic  bool      `json:"is_public"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Tag struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

// SearchMembersRow is the shape returned by the SearchMembers query,
// including the computed relevance rank.
type SearchMembersRow struct {
	ID       uuid.UUID `json:"id"`
	FullName string    `json:"full_name"`
	Headline *string   `json:"headline"`
	Bio      *string   `json:"bio"`
	Location *string   `json:"location"`
	Links    []byte    `json:"links"`
	Rank     float32   `json:"rank"`
}

type CommunityInfo struct {
	ID        int32     `json:"id"`
	Slug      string    `json:"slug"`
	Title     string    `json:"title"`
	Body      string    `json:"body"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// SearchCommunityInfoRow is the shape returned by the SearchCommunityInfo
// query, including the computed relevance rank.
type SearchCommunityInfoRow struct {
	ID    int32   `json:"id"`
	Slug  string  `json:"slug"`
	Title string  `json:"title"`
	Body  string  `json:"body"`
	Rank  float32 `json:"rank"`
}
