// Code generated by sqlc. DO NOT EDIT.
// Source: internal/store/sql/projects.sql
package queries

import (
	"context"

	"github.com/google/uuid"
)

const createProject = `
INSERT INTO projects (name, description, status, link)
VALUES ($1, $2, $3, $4)
RETURNING id, name, description, status, link, created_at, updated_at
`

type CreateProjectParams struct {
	Name        string
	Description *string
	Status      string
	Link        *string
}

func (q *Queries) CreateProject(ctx context.Context, p CreateProjectParams) (Project, error) {
	var pr Project
	err := q.db.QueryRow(ctx, createProject,
		p.Name, p.Description, p.Status, p.Link,
	).Scan(&pr.ID, &pr.Name, &pr.Description, &pr.Status, &pr.Link, &pr.CreatedAt, &pr.UpdatedAt)
	return pr, err
}

const getProjectByID = `
SELECT id, name, description, status, link, created_at, updated_at
FROM projects
WHERE id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error) {
	var pr Project
	err := q.db.QueryRow(ctx, getProjectByID, id).Scan(
		&pr.ID, &pr.Name, &pr.Description, &pr.Status, &pr.Link, &pr.CreatedAt, &pr.UpdatedAt,
	)
	return pr, err
}

const searchProjects = `
SELECT
    id,
    name,
    description,
    status,
    link,
    ts_rank(search_vector, plainto_tsquery('english', $1)) AS rank
FROM projects
WHERE search_vector @@ plainto_tsquery('english', $1)
ORDER BY rank DESC
LIMIT $2
`

func (q *Queries) SearchProjects(ctx context.Context, query string, resultLimit int32) ([]SearchProjectsRow, error) {
	rows, err := q.db.Query(ctx, searchProjects, query, resultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []SearchProjectsRow
	for rows.Next() {
		var r SearchProjectsRow
		if err := rows.Scan(&r.ID, &r.Name, &r.Description, &r.Status, &r.Link, &r.Rank); err != nil {
			return nil, err
		}
		results = append(results, r)
	}
	return results, rows.Err()
}

const attachMemberToProject = `
INSERT INTO project_members (project_id, member_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

func (q *Queries) AttachMemberToProject(ctx context.Context, projectID uuid.UUID, memberID uuid.UUID) error {
	_, err := q.db.Exec(ctx, attachMemberToProject, projectID, memberID)
	return err
}

const attachTagToProject = `
INSERT INTO project_tags (project_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

func (q *Queries) AttachTagToProject(ctx context.Context, projectID uuid.UUID, tagID int32) error {
	_, err := q.db.Exec(ctx, attachTagToProject, projectID, tagID)
	return err
}

const listProjectMembers = `
SELECT m.id, m.full_name
FROM members m
JOIN project_members pm ON pm.member_id = m.id
WHERE pm.project_id = $1 AND m.is_public = TRUE
`

type ListProjectMembersRow struct {
	ID       uuid.UUID `json:"id"`
	FullName string    `json:"full_name"`
}

func (q *Queries) ListProjectMembers(ctx context.Context, projectID uuid.UUID) ([]ListProjectMembersRow, error) {
	rows, err := q.db.Query(ctx, listProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var members []ListProjectMembersRow
	for rows.Next() {
		var m ListProjectMembersRow
		if err := rows.Scan(&m.ID, &m.FullName); err != nil {
			return nil, err
		}
		members = append(members, m)
	}
	return members, rows.Err()
}

const listProjectTags = `
SELECT t.id, t.name
FROM tags t
JOIN project_tags pt ON pt.tag_id = t.id
WHERE pt.project_id = $1
`

func (q *Queries) ListProjectTags(ctx context.Context, projectID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listProjectTags, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var tags []Tag
	for rows.Next() {
		var t Tag
		if err := rows.Scan(&t.ID, &t.Name); err != nil {
			return nil, err
		}
		tags = append(tags, t)
	}
	return tags, rows.Err()
}
