// Code generated by sqlc. DO NOT EDIT.
// Source: internal/store/sql/tags.sql
package queries

import (
	"context"

	"github.com/google/uuid"
)

const upsertTag = `
INSERT INTO tags (name)
VALUES ($1)
ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
RETURNING id, name
`

func (q *Queries) UpsertTag(ctx context.Context, name string) (Tag, error) {
	var t Tag
	err := q.db.QueryRow(ctx, upsertTag, name).Scan(&t.ID, &t.Name)
	return t, err
}

const attachTagToMember = `
INSERT INTO member_tags (member_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

func (q *Queries) AttachTagToMember(ctx context.Context, memberID uuid.UUID, tagID int32) error {
	_, err := q.db.Exec(ctx, attachTagToMember, memberID, tagID)
	return err
}

const searchMembersByTag = `
SELECT DISTINCT m.id, m.full_name, m.headline, m.bio, m.location, m.links
FROM members m
JOIN member_tags mt ON mt.member_id = m.id
JOIN tags t ON t.id = mt.tag_id
WHERE t.name = $1 AND m.is_public = TRUE
LIMIT $2
`

func (q *Queries) SearchMembersByTag(ctx context.Context, tagName string, resultLimit int32) ([]Member, error) {
	rows, err := q.db.Query(ctx, searchMembersByTag, tagName, resultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var members []Member
	for rows.Next() {
		var m Member
		if err := rows.Scan(&m.ID, &m.FullName, &m.Headline, &m.Bio, &m.Location, &m.Links); err != nil {
			return nil, err
		}
		members = append(members, m)
	}
	return members, rows.Err()
}
